name: Determine Version

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{secrets.TOKEN}}

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Execute Determine Version Utility Script
        run: |
          source .venv/bin/activate
          python3 determine_version.py
